# general
optim: adam
optim_conf:
    lr: 0.001
accum_grad: 2
grad_clip: 5
init: xavier_uniform
batch_type: folded
batch_size: 64
max_epoch: 100
patience: 5

scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

# criterion
val_scheduler_criterion:
    - valid
    - acc
early_stopping_criterion:
    - valid
    - acc
    - max
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

# MTL
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

# network
encoder: transformer
encoder_conf:
    input_layer: conv2d
    num_blocks: 12
    linear_units: 2048
    attention_heads: 4
    dropout_rate: 0.1
    attention_dropout_rate: 0.0
decoder: transformer
decoder_conf:
    num_blocks: 6
    linear_units: 2048
    attention_heads: 4
    dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
